openapi: 3.0.3
info:
  title: Authentication & Authorization API
  version: 1.0.0
  description: |
    Comprehensive API for user authentication, authorization, and two-factor authentication (2FA).

    **Response Format:**
    - Success: `{ status: "success", data: {...} }`
    - Fail: `{ status: "fail", data: { message: "...", ...} }`
    - Error: `{ status: "error", message: "..." }`
  contact:
    name: Ahmed Reda
    url: https://github.com/AhmedRedaG/Authentication-Authorization-CAT
    email: ahmedrf.dev@gmail.com

servers:
  - url: http://localhost:3000/api/v1/
    description: Local server
